### ISSUE TITLE
主界面pip安装无法使用

### ISSUE THREAD

**Issue by winderosion1** [PauperZ/SSRSpeedN#3]
开代理的情况下报错：

> Collecting pip
  Downloading https://files.pythonhosted.org/packages/ca/31/b88ef447d595963c01060998cb329251648acf4a067721b0452c45527eb8/pip-21.2.4-py3-none-any.whl (1.6MB)
     |████████████████████████████████| 1.6MB 819kB/s
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-21.2.4
ERROR: Exception:
Traceback (most recent call last):
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\cli\base_command.py", line 173, in _main
    status = self.run(options, args)
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\cli\req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\commands\install.py", line 315, in run
    requirement_set = resolver.resolve(
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 341, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 140, in __bool__
    return any(self)
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 128, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 29, in _iter_built
    for version, func in infos:
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 272, in iter_index_candidate_infos
    result = self._finder.find_best_candidate(
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\index\package_finder.py", line 851, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\index\package_finder.py", line 798, in find_all_candidates
    page_candidates = list(page_candidates_it)
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\index\sources.py", line 134, in page_candidates
    yield from self._candidates_from_page(self._link)
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\index\package_finder.py", line 758, in process_project_url
    html_page = self._link_collector.fetch_page(project_url)
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\index\collector.py", line 490, in fetch_page
    return _get_html_page(location, session=self.session)
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\index\collector.py", line 400, in _get_html_page
    resp = _get_html_response(url, session=session)
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\index\collector.py", line 115, in _get_html_response
    resp = session.get(
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\network\session.py", line 454, in request
    return super().request(method, url, *args, **kwargs)
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 53, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "c:\users\12875\appdata\local\programs\python\python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "c:\users\12875\appdata\local\programs\python\python38\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname

不开代理的情况下报错：

> 请选择（1~5）：
[1,2,3,4,5]?2
Requirement already satisfied: pip in c:\users\12875\appdata\local\programs\python\python38\lib\site-packages (21.2.4)
Collecting pillow
  Downloading Pillow-8.3.1-1-cp38-cp38-win_amd64.whl (3.2 MB)
     |████                            | 368 kB 4.4 kB/s eta 0:10:51ERROR: Exception:
Traceback (most recent call last):
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\urllib3\response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "c:\users\12875\appdata\local\programs\python\python38\lib\http\client.py", line 454, in read
    n = self.readinto(b)
  File "c:\users\12875\appdata\local\programs\python\python38\lib\http\client.py", line 498, in readinto
    n = self.fp.readinto(b)
  File "c:\users\12875\appdata\local\programs\python\python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "c:\users\12875\appdata\local\programs\python\python38\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "c:\users\12875\appdata\local\programs\python\python38\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\cli\base_command.py", line 173, in _main
>     status = self.run(options, args)
>   File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\cli\req_command.py", line 203, in wrapper
>     return func(self, options, args)
>   File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\commands\install.py", line 315, in run
>     requirement_set = resolver.resolve(
>   File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 94, in resolve
>     result = self._result = resolver.resolve(
>   File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 472, in resolve
>     state = resolution.resolve(requirements, max_rounds=max_rounds)
>   File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 341, in resolve
>     self._add_to_criteria(self.state.criteria, r, parent=None)
>   File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
>     if not criterion.candidates:
>   File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
>     return bool(self._sequence)
>   File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 140, in __bool__
>     return any(self)
>   File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 128, in <genexpr>
>     return (c for c in iterator if id(c) not in self._incompatible_ids)
>   File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 32, in _iter_built
>     candidate = func()
>   File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 204, in _make_candidate_from_link
>     self._link_candidate_cache[link] = LinkCandidate(
>   File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 295, in __init__
>     super().__init__(
>   File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
>     self.dist = self._prepare()
>   File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 227, in _prepare
>     dist = self._prepare_distribution()
>   File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 305, in _prepare_distribution
>     return self._factory.preparer.prepare_linked_requirement(
>   File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\operations\prepare.py", line 508, in prepare_linked_requirement
>     return self._prepare_linked_requirement(req, parallel_builds)
>   File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\operations\prepare.py", line 550, in _prepare_linked_requirement
>     local_file = unpack_url(
>   File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\operations\prepare.py", line 239, in unpack_url
>     file = get_http_url(
>   File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\operations\prepare.py", line 102, in get_http_url
>     from_path, content_type = download(link, temp_dir.path)
>   File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\network\download.py", line 145, in __call__
>     for chunk in chunks:
>   File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\cli\progress_bars.py", line 144, in iter
>     for x in it:
>   File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
>     for chunk in response.raw.stream(
>   File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\urllib3\response.py", line 576, in stream
>     data = self.read(amt=amt, decode_content=decode_content)
>   File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\urllib3\response.py", line 541, in read
>     raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
>   File "c:\users\12875\appdata\local\programs\python\python38\lib\contextlib.py", line 131, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "c:\users\12875\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher
>     raise ReadTimeoutError(self._pool, None, "Read timed out.")
> pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

**Comment by Je11ySun** [comment]
##### 请放在SSRSpeed目录下运行 #####

python: can't open file 'C:\\WINDOWS\\system32\\main.py': [Errno 2] No such file or directory
当前已获取管理员权限
已安装V2ray-core
====================================
1：开始测速（自定义设置）
2：首次运行前安装pip和相关支持（需要管理员权限）
3：参数查阅
4：当前SSRSpeed版本
5：为本次运行获取管理员权限
====================================
请选择（1~5）：
[1,2,3,4,5]?5


已获取管理员权限

请按任意键继续. . .
====================================
1：开始测速（自定义设置）
2：首次运行前安装pip和相关支持（需要管理员权限）
3：参数查阅
4：当前SSRSpeed版本
5：为本次运行获取管理员权限
====================================
请选择（1~5）：
[1,2,3,4,5]?2
Requirement already satisfied: pip in c:\users\jelly sun\appdata\local\programs\python\python310\lib\site-packages (21.3.1)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))': /simple/pip/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))': /simple/pip/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))': /simple/pip/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))': /simple/pip/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))': /simple/pip/
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))) - skipping
ERROR: Invalid requirement: 'windows\\SSRSpeedN-main\\\\requirements.txt'
Hint: It looks like a path. File 'windows\SSRSpeedN-main\\requirements.txt' does not exist.
请按任意键继续. . .

**Comment by PauperZ** [comment]
@Je11ySun 网络问题，检测一下本地网络，或者挂系统代理安装

**Comment by wei727** [comment]
> @Je11ySun网络问题，检测一下本地网络，或者挂系统代理安装

大佬小白问下：'pip3' 不是内部或外部命令，也不是可运行的程序
或批处理文件。这种情况怎么处理！
