### ISSUE TITLE
检测时报错：violation of protocol

### ISSUE THREAD

**Issue by zhu-yuefeng** [PauperZ/SSRSpeedN#32]
我成功以管理员身份安装所需的python包，但在打开代理、以用户身份执行链接检测时，遇到疑似SSL协议冲突的问题。
以下是CMD窗口的部分信息：

****** Import Hint 重要提示******
ChenBilly yyds！
*********************************
Press ENTER to conitnue or Crtl+C to exit.
[2022-06-04 13:40:49,242][INFO][9336][main.py:91]SSRSpeed 1.03, Web Api Version 0.5.2
E:\SSRSpeedN-main\main.py:100: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn("Requirements check skipped.")
[2022-06-04 13:40:49,247][WARNING][9336][main.py:100]Requirements check skipped.
[2022-06-04 13:40:49,248][INFO][9336][config_parser.py:177]Reading 【这里是我的订阅链接，出于隐私考虑隐去】
Traceback (most recent call last):
  File "E:\Program Files (x86)\Python\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "E:\Program Files (x86)\Python\lib\site-packages\urllib3\connectionpool.py", line 994, in _prepare_proxy
    conn.connect()
  File "E:\Program Files (x86)\Python\lib\site-packages\urllib3\connection.py", line 364, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "E:\Program Files (x86)\Python\lib\site-packages\urllib3\connection.py", line 499, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "E:\Program Files (x86)\Python\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "E:\Program Files (x86)\Python\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "E:\Program Files (x86)\Python\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\Program Files (x86)\Python\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "E:\Program Files (x86)\Python\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Program Files (x86)\Python\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "E:\Program Files (x86)\Python\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "E:\Program Files (x86)\Python\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='66ding.men', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=bd3e0145c10f3416f634ee129ebbdded (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\SSRSpeedN-main\main.py", line 218, in <module>
    sc.console_setup(
  File "E:\SSRSpeedN-main\ssrspeed\core\ssrspeed_core.py", line 119, in console_setup
    self.__parser.read_subscription(url.split(" "))
  File "E:\SSRSpeedN-main\ssrspeed\config_parser\config_parser.py", line 214, in read_subscription
    rep = requests.get(url,headers = header, timeout=15)
  File "E:\Program Files (x86)\Python\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "E:\Program Files (x86)\Python\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\Program Files (x86)\Python\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Program Files (x86)\Python\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "E:\Program Files (x86)\Python\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='66ding.men', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=bd3e0145c10f3416f634ee129ebbdded (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
请按任意键继续. . .

**Comment by tech-fever** [comment]
朋友，去重置订阅，你暴露订阅了！
