### ISSUE TITLE
请问这个错误是什么？

### ISSUE THREAD

**Issue by doomzc** [PauperZ/SSRSpeedN#39]
Collecting aiohttp_socks
  Using cached aiohttp_socks-0.7.1-py3-none-any.whl (9.3 kB)
Collecting pynat
  Using cached pynat-0.7.0.tar.gz (7.1 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-_8q8khy6\pynat_4cf1f56bef3945618cbaceeb2460b58d\setup.py", line 7, in <module>
          from pynat import __version__, url
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-_8q8khy6\pynat_4cf1f56bef3945618cbaceeb2460b58d\pynat.py", line 29, in <module>
          from six import text_type
      ModuleNotFoundError: No module named 'six'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by PauperZ** [comment]
目测是python和pip版本问题，是不是太新了？

**Comment by doomzc** [comment]
python 我下载了旧版还是。。pip我试试

**Comment by Wanna026** [comment]
> 我也是和你一样的报错，咋解决的哇呜呜呜。

**Comment by whyisshen** [comment]
https://blog.csdn.net/life_isshort/article/details/92674976 我看的这个解决了问题，python版本是3.7.0

**Comment by fengziX** [comment]
我装了six还是不行....
