### ISSUE TITLE
【已解决】

### ISSUE THREAD

**Issue by di7gan** [PauperZ/SSRSpeedN#46]
`****** Import Hint 重要提示******
ChenBilly yyds！
*********************************
Press ENTER to conitnue or Crtl+C to exit.
[2022-12-06 12:33:27,826][INFO][10220][main.py:91]SSRSpeed 1.03, Web Api Version 0.5.2
D:\Netch\SSRSpeedN-1.03\SSRSpeedN-1.03\main.py:100: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn("Requirements check skipped.")
[2022-12-06 12:33:27,828][WARNING][10220][main.py:100]Requirements check skipped.
[2022-12-06 12:33:27,829][INFO][10220][config_parser.py:177]Reading 这里是订阅链接

这里省略

[2022-12-06 12:33:29,235][INFO][10220][export_result.py:723]Result exported as ./results/2022-12-06-12-33-29.json
Traceback (most recent call last):
  File "D:\Netch\SSRSpeedN-1.03\SSRSpeedN-1.03\main.py", line 247, in <module>
    sc.start_test(options.use_ssr_cs)
  File "D:\Netch\SSRSpeedN-1.03\SSRSpeedN-1.03\ssrspeed\core\ssrspeed_core.py", line 136, in start_test
    self.__exportResult()
  File "D:\Netch\SSRSpeedN-1.03\SSRSpeedN-1.03\ssrspeed\core\ssrspeed_core.py", line 180, in __exportResult
    er.export(self.__results,split,exportType,self.sortMethod)
  File "D:\Netch\SSRSpeedN-1.03\SSRSpeedN-1.03\ssrspeed\result\export_result.py", line 76, in export
    self.__exportAsPng(result)
  File "D:\Netch\SSRSpeedN-1.03\SSRSpeedN-1.03\ssrspeed\result\export_result.py", line 626, in __exportAsPng
    Avgrate = (sum - sum0) / totalTraffic
ZeroDivisionError: division by zero

`
查看了一下文件：./results/2022-12-06-12-33-29.json，里面只有[]。

**Comment by di7gan** [comment]
测试系统WIN11
PYTHON -V：Python 3.9.6
PIP3 -V：pip 22.3.1 from C:\Users\caoxing\AppData\Local\Programs\Python\Python39\lib\site-packages\pip (python 3.9)

**Comment by di7gan** [comment]
![屏幕截图 2022-12-06 123726](https://user-images.githubusercontent.com/20412710/205816623-1bdf4474-cdd1-4b9f-97f4-c31915f584cb.png)

**Comment by AirportR** [comment]
> Requirements

你是不是没更新到最新版，我看到最新版的代码已经修复这个问题。

**Comment by di7gan** [comment]
> > Requirements
> 
> 你是不是没更新到最新版，我看到最新版的代码已经修复这个问题。

下载的最新V1.03版本，同时使用download zip方式也是一样。

那我全部重新在试试

**Comment by ItsFimall** [comment]
请 close 这个 issue
