### ISSUE TITLE
输出图片错误

### ISSUE THREAD

**Issue by danielzi** [PauperZ/SSRSpeedN#51]
[2023-03-31 18:00:35,368][INFO][6004][export_result.py:723]Result exported as ./results/2023-03-31-18-00-35.json
Traceback (most recent call last):
  File "C:\Users\L\Downloads\SSRSpeedN-1.03\main.py", line 247, in <module>
    sc.start_test(options.use_ssr_cs)
  File "C:\Users\L\Downloads\SSRSpeedN-1.03\ssrspeed\core\ssrspeed_core.py", line 136, in start_test
    self.__exportResult()
  File "C:\Users\L\Downloads\SSRSpeedN-1.03\ssrspeed\core\ssrspeed_core.py", line 180, in __exportResult
    er.export(self.__results,split,exportType,self.sortMethod)
  File "C:\Users\L\Downloads\SSRSpeedN-1.03\ssrspeed\result\export_result.py", line 76, in export
    self.__exportAsPng(result)
  File "C:\Users\L\Downloads\SSRSpeedN-1.03\ssrspeed\result\export_result.py", line 611, in __exportAsPng
    sum0 = int(test.readline())
ValueError: invalid literal for int() with base 10: ''

**Comment by PauperZ** [comment]
更新即可
