### ISSUE TITLE
这是什么情况？

### ISSUE THREAD

**Issue by acgniubi** [PauperZ/SSRSpeedN#57]
Requirement already satisfied: pip in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (23.1.2)
Requirement already satisfied: six in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from -r D:\SSRSpeedN-1.04\\requirements.txt (line 1)) (1.16.0)
Collecting pillow (from -r D:\SSRSpeedN-1.04\\requirements.txt (line 2))
  Using cached Pillow-9.5.0-cp311-cp311-win_amd64.whl (2.5 MB)
Requirement already satisfied: requests in c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages (from -r D:\SSRSpeedN-1.04\\requirements.txt (line 3)) (2.31.0)
Collecting pysocks (from -r D:\SSRSpeedN-1.04\\requirements.txt (line 5))
  Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Collecting flask (from -r D:\SSRSpeedN-1.04\\requirements.txt (line 6))
  Using cached Flask-2.3.2-py3-none-any.whl (96 kB)
Collecting flask-cors (from -r D:\SSRSpeedN-1.04\\requirements.txt (line 7))
  Using cached Flask_Cors-3.0.10-py2.py3-none-any.whl (14 kB)
Collecting pyyaml (from -r D:\SSRSpeedN-1.04\\requirements.txt (line 8))
  Using cached PyYAML-6.0-cp311-cp311-win_amd64.whl (143 kB)
Collecting aiohttp (from -r D:\SSRSpeedN-1.04\\requirements.txt (line 9))
  Using cached aiohttp-3.8.4-cp311-cp311-win_amd64.whl (317 kB)
Collecting aiohttp_socks (from -r D:\SSRSpeedN-1.04\\requirements.txt (line 10))
  Using cached aiohttp_socks-0.8.0-py3-none-any.whl (9.4 kB)
Collecting pynat (from -r D:\SSRSpeedN-1.04\\requirements.txt (line 11))
  Using cached pynat-0.7.0.tar.gz (7.1 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-27k7c8x5\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-27k7c8x5\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-27k7c8x5\overlay\Lib\site-packages\setuptools\build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-27k7c8x5\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 7, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-k3nb8fy1\pynat_dc3ad7b92e1e4f7184316f3c570a0b37\pynat.py", line 29, in <module>
          from six import text_type
      ModuleNotFoundError: No module named 'six'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
请按任意键继续. . .

**Comment by Luuucy987** [comment]
这个问题是pip install pynat安装的报错
具体什么原因我也不知道，我也在试着解决

**Comment by klpk1214** [comment]
我也是这个问题，烦死

**Comment by Luuucy987** [comment]
已尝试过pip install six，可能是pillow的问题，我再排查一下，谢谢

**Comment by lvxj11** [comment]
如果还不行换到python3.9试试。python3.9已测试可以运行。

**Comment by Luuucy987** [comment]
好的谢谢

**Comment by krkrchan** [comment]
请问这个问题解决了吗
