### ISSUE TITLE
订阅链接为Clash时，无法获取节点信息

### ISSUE THREAD

**Issue by gzw02140** [PauperZ/SSRSpeedN#6]
当订阅文件为clash配置文件时，就无法获得节点信息

> [2021-09-24 16:44:47,798][INFO][19144][main.py:91]SSRSpeed 1.01, Web Api Version 0.5.2
C:\Software\SSRSpeedN-main\main.py:100: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn("Requirements check skipped.")
[2021-09-24 16:44:47,800][WARNING][19144][main.py:100]Requirements check skipped.
[2021-09-24 16:44:47,800][INFO][19144][config_parser.py:176]Reading ……
[2021-09-24 16:44:54,487][INFO][19144][config_parser.py:220]Base64 decode failed.
Traceback (most recent call last):
  File "C:\Software\SSRSpeedN-main\main.py", line 218, in <module>
    sc.console_setup(
  File "C:\Software\SSRSpeedN-main\ssrspeed\core\ssrspeed_core.py", line 119, in console_setup
    self.__parser.read_subscription(url.split(" "))
  File "C:\Software\SSRSpeedN-main\ssrspeed\config_parser\config_parser.py", line 224, in read_subscription
    self.__nodes.extend(self.__parse_clash(rep))
  File "C:\Software\SSRSpeedN-main\ssrspeed\config_parser\config_parser.py", line 132, in __parse_clash
    pc.parse_config(clash_cfg)
  File "C:\Software\SSRSpeedN-main\ssrspeed\config_parser\clash_parser.py", line 135, in parse_config
    for cfg in clash_cfg["Proxy"]:
KeyError: 'Proxy'

**Comment by PauperZ** [comment]
更新至最新版即可
