### ISSUE TITLE
订阅提示base64解码错误？

### ISSUE THREAD

**Issue by Joackk** [PauperZ/SSRSpeedN#74]
在对一些订阅进行测速提示如下错误，大佬这是啥子情况啊
python main.py -u xxxx
****** Import Hint 重要提示******
ChenBilly yyds！
*********************************
Press ENTER to conitnue or Crtl+C to exit.
[2024-01-15 18:17:46,089][INFO][30744][main.py:91]SSRSpeed 1.04, Web Api Version 0.5.2
[2024-01-15 18:17:46,089][INFO][30744][platform_check.py:9]Platform Info : Windows-10-10.0.19045-SP0
[2024-01-15 18:17:46,089][INFO][30744][requirements_check.py:57]Checking ./clients/shadowsocks-libev/obfs-local.exe
[2024-01-15 18:17:46,090][INFO][30744][requirements_check.py:57]Checking ./clients/shadowsocks-libev/simple-obfs.exe
[2024-01-15 18:17:46,090][INFO][30744][requirements_check.py:57]Checking ./clients/shadowsocks-libev/ss-local.exe
[2024-01-15 18:17:46,091][INFO][30744][requirements_check.py:57]Checking ./clients/shadowsocks-libev/ss-tunnel.exe
[2024-01-15 18:17:46,093][INFO][30744][requirements_check.py:57]Checking ./clients/shadowsocksr-libev/libssp-0.dll
[2024-01-15 18:17:46,093][INFO][30744][requirements_check.py:57]Checking ./clients/shadowsocksr-libev/libwinpthread-1.dll
[2024-01-15 18:17:46,093][INFO][30744][requirements_check.py:57]Checking ./clients/shadowsocksr-libev/libpcre-1.dll
[2024-01-15 18:17:46,093][INFO][30744][requirements_check.py:57]Checking ./clients/shadowsocksr-libev/libcrypto-1_1.dll
[2024-01-15 18:17:46,094][INFO][30744][requirements_check.py:57]Checking ./clients/shadowsocksr-libev/ssr-local.exe
[2024-01-15 18:17:46,094][INFO][30744][requirements_check.py:57]Checking ./clients/shadowsocksr-win/shadowsocksr.exe
[2024-01-15 18:17:46,094][INFO][30744][requirements_check.py:57]Checking ./clients/v2ray-core/v2ctl.exe
[2024-01-15 18:17:46,094][INFO][30744][requirements_check.py:57]Checking ./clients/v2ray-core/v2ray.exe
[2024-01-15 18:17:46,794][INFO][30744][config_parser.py:191]Reading https://sub.taco.homes/api/v1/client/subscribe?token=wvaa91090t0vvz79t28a3342p4p2hb8i
[2024-01-15 18:17:48,165][INFO][30744][config_parser.py:252]Base64 decode failed.
Traceback (most recent call last):
  File "F:\Software2\SSRSpeedN-main\main.py", line 218, in <module>
    sc.console_setup(
  File "F:\Software2\SSRSpeedN-main\ssrspeed\core\ssrspeed_core.py", line 176, in console_setup
    self.__parser.read_subscription(url.split(" "))
  File "F:\Software2\SSRSpeedN-main\ssrspeed\config_parser\config_parser.py", line 256, in read_subscription
    self.__nodes.extend(self.__parse_clash(rep))
  File "F:\Software2\SSRSpeedN-main\ssrspeed\config_parser\config_parser.py", line 144, in __parse_clash
    pc.parse_config(clash_cfg)
  File "F:\Software2\SSRSpeedN-main\ssrspeed\config_parser\clash_parser.py", line 184, in parse_config
    for cfg in clash_cfg["proxies"]:
KeyError: 'proxies'

**Comment by ItsFimall** [comment]
检查订阅链接

**Comment by w2Seven7** [comment]
我也遇到了 vmess协议的机场测速正常  但是vless协议的不行 看错误代码也是提示转码失败 不懂怎么解决
