### ISSUE TITLE
请教一下，安装pynat 报six模块不存在怎么弄，就卡在这里了

### ISSUE THREAD

**Issue by yonee77** [PauperZ/SSRSpeedN#77]
![image](https://github.com/PauperZ/SSRSpeedN/assets/76467513/962eddd3-62f0-404c-aa69-e766897e7c10)
six已经安装了！

pip3 install pynat
Collecting pynat
  Using cached pynat-0.7.0.tar.gz (7.1 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "C:\Users\ads\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\ads\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ads\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ads\AppData\Local\Temp\pip-build-env-3wp2bq94\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ads\AppData\Local\Temp\pip-build-env-3wp2bq94\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\ads\AppData\Local\Temp\pip-build-env-3wp2bq94\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\ads\AppData\Local\Temp\pip-build-env-3wp2bq94\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 7, in <module>
        File "C:\Users\ads\AppData\Local\Temp\pip-install-ndr_kh_h\pynat_994f05b0c54847e7b85bc225c712f97f\pynat.py", line 29, in <module>
          from six import text_type
      ModuleNotFoundError: No module named 'six'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by yonee77** [comment]
解决了，
pip install six

pip install setuptools wheel

pip install --no-use-pep517 pynat

**Comment by zqzq3** [comment]
fixed for me
